name: PHP 8.2 docker image

on:
  push:
    branches: [ "main" ]
    paths:
      - '8.2/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '8.2/**'

jobs:
  build-82:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DK_HUB_USR }}
          password: ${{ secrets.DK_HUB }}

      - name: Build the Docker image for PHP 8.2
        run: |
          make 82 type=fpm
          make 82 type=fpm env=dev
