name: PHP 8.3 docker image

on:
  push:
    branches: [ "main" ]
    paths:
      - '8.3/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '8.3/**'

jobs:
  build-83:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DK_HUB_USR }}
          password: ${{ secrets.DK_HUB }}

      - name: Build the Docker image for PHP 8.3
        run: |
          make 83 type=fpm
          make 83 type=fpm env=dev
