name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DK_HUB_USR }}
          password: ${{ secrets.DK_HUB }}

      - uses: actions/checkout@v3
        name: Build the Docker image for PHP 8.1
        run: |
          make 81 env=prod
          make 81 env=dev
